### ISSUE TITLE
setRegister after return? How is that supposed to work?

### ISSUE THREAD

**Issue by neilyoung** [sparkfun/ToF_Range_Finder_Sensor-VL6180#1]
uint8_t VL6180x::getDistance()
{
  VL6180x_setRegister(VL6180X_SYSRANGE_START, 0x01); //Start Single shot mode
  delay(10);
  return VL6180x_getRegister(VL6180X_RESULT_RANGE_VAL);
  VL6180x_setRegister(VL6180X_SYSTEM_INTERRUPT_CLEAR, 0x07);
  //	return distance;
}

**Comment by Grahldg** [comment]
Hi @neilyoung ,

This was corrected in a recent commit.  I did some testing and did not notice an aberrant behavior, but if you notice any strange behaviors please let me know.

**Comment by neilyoung** [comment]
@Grahldg Wow, already forgot that I ever have dealt with this. Can't remember either :)
